#!/usr/bin/env bash

/opt/python/cp38-cp38/bin/pip install -r /io/requirements-dev.txt
/opt/python/cp38-cp38/bin/pip wheel /io/ --no-deps -w /io/dist/
for whl in /io/dist/*.whl; do
  auditwheel repair "$whl" --plat "$PLAT" -w /io/dist/
  rm -rf "$whl"
done