#!/usr/bin/env bash

# Get project root relative to this script
prjroot="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
[[ -z "$prjroot" ]] && { echo "Script location cannot be root." ; exit 1; }

"${prjroot}"/tools/clean

# Build bdist_wheel
printf "\nBuilding bdist_wheel\n"
(cd "${prjroot}"; python setup.py bdist_wheel)

printf "\nTo be uploaded:\n"
ls -lah "${prjroot}"/dist
printf "\n"

# Upload to PyPI
twine upload "${prjroot}"/dist/*